version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    hostname: master
    container_name: rabbitmq
    restart: always
    networks:
      - backend
    expose:
      - "5672"
      - "15672"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data:/var/lib/rabbitmq3
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

networks:
  backend:
    name: backend
    driver: bridge