version: "3.9"

services:
  postgres:
    image: postgres:14.5
    environment: # https://github.com/docker-library/docs/blob/master/postgres/README.md#environment-variables
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data