version: '3.9'

services:
  nginx:
    image: nginx:1.23.1
    ports:
      - "443:443" 
      - "80:80" 
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/certs/myesn.io.pem:/etc/ssl/certs/site.pem
      - ./ssl/private/myesn.io-key.pem:/etc/ssl/private/site-key.pem